name: ci

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
          build-args: |
            POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}

            # Additional steps to save the Docker image as a .tar file
      - name: Save Docker image to .tar
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
          docker save ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest > image.tar

      - name: Upload image tarball
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: image.tar
